site_name: My Garden
docs_dir: garden
site_url: https://josekilo.github.io/garden/
theme:
  name: material
  favicon: img/favicon.ico
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
