site_name: My Garden
docs_dir: garden
site_url: https://josekilo.github.io/garden/
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
